---
- hosts: test
  become: yes
  become_method: sudo
  become_user: root
  tasks:

  - name: gather os specific variables
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
      - "{{ ansible_distribution }}.yml"
    tags: vars

  - debug:
      var: result_dict
